# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mud.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmud.proto\x12\x03mud\".\n\x0cLoginRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"E\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\"#\n\rLogoutRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"2\n\x0eLogoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"!\n\x0f\x43ommandResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"&\n\x10KeepAliveRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"$\n\x11KeepAliveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"*\n\x15StreamMessagesRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\t\")\n\x16StreamMessagesResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x84\x02\n\nMudService\x12;\n\x0e\x45xecuteCommand\x12\x13.mud.CommandRequest\x1a\x14.mud.CommandResponse\x12\x30\n\x05Login\x12\x11.mud.LoginRequest\x1a\x12.mud.LoginResponse\"\x00\x12:\n\tKeepAlive\x12\x15.mud.KeepAliveRequest\x1a\x16.mud.KeepAliveResponse\x12K\n\x0eStreamMessages\x12\x1a.mud.StreamMessagesRequest\x1a\x1b.mud.StreamMessagesResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mud_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGINREQUEST']._serialized_start=18
  _globals['_LOGINREQUEST']._serialized_end=64
  _globals['_LOGINRESPONSE']._serialized_start=66
  _globals['_LOGINRESPONSE']._serialized_end=135
  _globals['_LOGOUTREQUEST']._serialized_start=137
  _globals['_LOGOUTREQUEST']._serialized_end=172
  _globals['_LOGOUTRESPONSE']._serialized_start=174
  _globals['_LOGOUTRESPONSE']._serialized_end=224
  _globals['_COMMANDREQUEST']._serialized_start=226
  _globals['_COMMANDREQUEST']._serialized_end=259
  _globals['_COMMANDRESPONSE']._serialized_start=261
  _globals['_COMMANDRESPONSE']._serialized_end=294
  _globals['_KEEPALIVEREQUEST']._serialized_start=296
  _globals['_KEEPALIVEREQUEST']._serialized_end=334
  _globals['_KEEPALIVERESPONSE']._serialized_start=336
  _globals['_KEEPALIVERESPONSE']._serialized_end=372
  _globals['_STREAMMESSAGESREQUEST']._serialized_start=374
  _globals['_STREAMMESSAGESREQUEST']._serialized_end=416
  _globals['_STREAMMESSAGESRESPONSE']._serialized_start=418
  _globals['_STREAMMESSAGESRESPONSE']._serialized_end=459
  _globals['_MUDSERVICE']._serialized_start=462
  _globals['_MUDSERVICE']._serialized_end=722
# @@protoc_insertion_point(module_scope)
